
services:
  app:
    build: .
    image: mi-api-login:latest
    container_name: mi-api-login-container
    ports:
      - "8181:8181"
    environment:
      - clave.archivoPEM=${CLAVE_ARCHIVO_PEM}
      - spring.datasource.url=jdbc:mysql://db:3306/db_usuarios
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.jwt.secretKey=${JWT_SECRET_KEY}
      - spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8
    container_name: mi-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=db_usuarios
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
