
services:
  app:
    build: .
    image: mi-api-login:latest
    container_name: mi-api-login-container
    ports:
      - "8181:8181"
    volumes:
      - C:\Users\mohab\Desktop:/mnt
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/db_usuarios
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

      - keystore.private.path=${RUTA_ALMACEN}
      - keystore.private.password=${PASSWORD_ALMACEN}
      - keystore.private.key-password=${PASSWORD_PRIVATE_KEY}
      - keystore.private.key-alias=${ALIAS_PRIVATE_KEY}
      - keystore.public.path=${RUTA_ALMACEN_PUBLICO}
      - keystore.public.password=${PASSWORD_ALMACEN_PUBLICO}
      - keystore.public.key-alias=${ALIAS_PUBLIC_KEY}

    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8
    container_name: mi-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=db_usuarios
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
